services:
  frontend:
    build:
      context: ./frontend
    image: printsync3d-frontend:latest
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
    image: printsync3d-backend:latest
    platform: linux/arm64
    privileged: true # give full device capabilities
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - PORT=8000
      - BAUD_RATE=115200
      - DATA_DIRECTORY=/app/data
    healthcheck:
      test: wget --spider -q http://localhost:8000/health
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - backenddata:/app/data
      - type: bind
        source: /dev # bind-mount entire /dev
        target: /dev
        bind:
          propagation: rshared
    networks:
      - app-network
    # Limit the amount of log files for small IoT
    # devices with limited amount of disk memory
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "3"

volumes:
  backenddata:

networks:
  app-network:
    driver: bridge