services:
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    privileged: true # give full device capabilities
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      - PORT=8000
      - BAUD_RATE=115200
      - DATA_DIRECTORY=/app/data
    healthcheck:
      test: wget --spider -q http://localhost:8000/health
      interval: 1s
      timeout: 5s
      retries: 5
    volumes:
      - backenddata:/app/data
      - type: bind
        source: /dev # bind-mount entire /dev
        target: /dev
        bind:
          propagation: rshared
    networks:
      - app-network

volumes:
  backenddata:

networks:
  app-network:
    driver: bridge